/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/fund/daily-info/nav": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * มูลค่าทรัพย์สินสุทธิ (NAV) ของกองทุนรวมรายวัน
     * @description ข้อมูลมูลค่าหน่วยลงทุน (Net Asset Value: NAV) ของกองทุนรวมในรูปแบบรายวัน โดยแสดงรายละเอียดจำนวนมูลค่าทรัพย์สินสุทธิของกองทุน (Net Asset), มูลค่าหน่วยลงทุน (NAV per unit), ราคาซื้อ–ขายปกติ และราคาซื้อ–ขายสำหรับการสับเปลี่ยนหน่วยลงทุน (Switching)
     */
    get: operations["getFundDailyInfoNAV"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description รายการ NAV หนึ่งแถว */
    FundNavDailyInfoItem: {
      /** @description เลขที่โครงการ ({Type}{ID}_YYYY) */
      proj_id?: string;
      /**
       * Format: date
       * @description วันที่ NAV (YYYY-MM-DD)
       */
      nav_date?: string;
      /** @description ชื่อย่อชนิดหน่วยลงทุน (Class Fund) หมายเหตุ: เป็น "main" ถ้าเป็นกองทุนที่ไม่ใช่ Class Fund */
      fund_class_name?: string;
      /** @description มูลค่าทรัพย์สินสุทธิ (บาท) */
      net_asset?: number;
      /** @description มูลค่าหน่วยลงทุน (บาท/หน่วย) */
      last_val?: number;
      /** @description รหัสอ้างอิงบริษัทจัดการที่เป็นผู้ส่งข้อมูล */
      unique_id?: string;
      /** @description ราคาขาย (บาท/หน่วย) */
      sell_price?: number;
      /** @description ราคาซื้อคืน (บาท/หน่วย) */
      buy_price?: number;
      /** @description ราคาขายสับเปลี่ยน (บาท/หน่วย) */
      sell_swap_price?: number;
      /** @description ราคาซื้อคืนสับเปลี่ยน (บาท/หน่วย) */
      buy_swap_price?: number;
      /**
       * Format: date-time
       * @description วันที่แก้ไขข้อมูลล่าสุด
       */
      last_upd_date?: string;
    };
    FundNavDailyInfoResponse: {
      /** @description ข้อความสถานะของการเรียก API */
      message?: string;
      /** @description จำนวนรายการที่ส่งกลับต่อครั้ง */
      page_size?: number;
      /** @description ค่า cursor ที่ได้รับจาก Response ล่าสุด (กรณีที่ค่า next_cursor = "" หมายถึงระบบส่งข้อมูลให้ครบทั้งหมดแล้ว ไม่มีหน้าถัดไป) */
      next_cursor?: string;
      /** @description รายการข้อมูลหลักที่ส่งกลับมา */
      items?: components["schemas"]["FundNavDailyInfoItem"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getFundDailyInfoNAV: {
    parameters: {
      query?: {
        /** @description ค่า cursor ล่าสุดที่ได้รับจากการตอบกลับก่อนหน้า (ใช้สำหรับโหลดข้อมูลเพิ่มเติม) */
        next_cursor?: string;
        /** @description จำนวนรายการข้อมูลต่อหน้าที่ต้องการให้ระบบส่งกลับ (ค่าเริ่มต้น 100) โดยรองรับค่าตั้งแต่ 1 ถึง 100 รายการ */
        page_size?: number;
        /** @description ระบุ proj_id เพื่อดึงข้อมูลของกองทุน 1 กอง */
        proj_id?: string;
        /** @description ระบุวันที่เริ่มต้นของ NAV ที่ต้องการดึงข้อมูล (รูปแบบ: YYYY-MM-DD) */
        start_nav_date?: string;
        /** @description ระบุวันที่สิ้นสุดของ NAV ที่ต้องการดึงข้อมูล (รูปแบบ: YYYY-MM-DD) */
        end_nav_date?: string;
        /** @description ชื่อชนิดหน่วยลงทุน */
        fund_class_name?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description รายการ NAV ตามเงื่อนไข */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "success",
           *       "page_size": 100,
           *       "next_cursor": "xxxx-xxx-xxx",
           *       "items": [
           *         {
           *           "proj_id": "M0004_2559",
           *           "unique_id": "C0000033452",
           *           "fund_class_name": "-",
           *           "nav_date": "2023-07-13",
           *           "net_asset": 248999361.26,
           *           "last_val": 15.0833,
           *           "sell_price": 15.3097,
           *           "buy_price": 15.0833,
           *           "sell_swap_price": 15.0833,
           *           "buy_swap_price": 15.3097,
           *           "last_upd_date": "2024-10-31T03:34:11Z"
           *         }
           *       ]
           *     }
           */
          "application/json": components["schemas"]["FundNavDailyInfoResponse"];
        };
      };
    };
  };
}
