/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/{proj_id}/dailynav/{nav_date}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 01. NAV กองทุนรวมรายวัน
     * @description <table style="width:100%">
     *       <tr>
     *       <th>ชื่อ Field</th>
     *       <th>รายละเอียด</th>
     *       </tr>
     *       <tr><td>last_upd_date</td><td>วันที่แก้ไขข้อมูลล่าสุด</td></tr>
     *       <tr><td>nav_date</td><td>วันที่ NAV (YYYY-MM-DD)</td></tr>
     *      <tr><td>class_abbr_name</td><td>ชื่อกองทุน</td></tr>
     *      <tr><td>net_asset</td><td>มูลค่าทรัพย์สินสุทธิ (บาท)</td></tr>
     *       <tr><td>last_val</td><td>มูลค่าหน่วยลงทุน (บาท/หน่วย)</td></tr>
     *       <tr><td>previous_val</td><td>มูลค่าหน่วยลงทุนของวันก่อนหน้า (บาท/หน่วย)</td></tr>
     *       <tr><td>amc_info</td><td></td></tr>
     *       <tr><td>&emsp;&emsp;&emsp;unique_id</td><td>รหัสอ้างอิงบริษัทจัดการที่เป็นผู้ส่งข้อมูล</td></tr>
     *       <tr><td>&emsp;&emsp;&emsp;sell_price</td><td>ราคาขาย (บาท/หน่วย)</td></tr>
     *       <tr><td>&emsp;&emsp;&emsp;buy_price</td><td>ราคาซื้อคืน (บาท/หน่วย)</td></tr>
     *       <tr><td>&emsp;&emsp;&emsp;sell_swap_price</td><td>ราคาขายสับเปลี่ยน (บาท/หน่วย)</td></tr>
     *       <tr><td>&emsp;&emsp;&emsp;buy_swap_price</td><td>ราคาซื้อคืนสับเปลี่ยน (บาท/หน่วย)</td></tr>
     *       <tr><td>&emsp;&emsp;&emsp;remark_th</td><td>หมายเหตุภาษาไทย</td></tr>
     *       <tr><td>&emsp;&emsp;&emsp;remark_en</td><td>หมายเหตุภาษาอังกฤษ</td></tr>
     *       </table>
     *       <br>
     *       <p>ที่มา: สมาคมบริษัทจัดการลงทุน (AIMC)</p>
     */
    get: operations["01-NAV-\u0E01\u0E2D\u0E07\u0E17\u0E38\u0E19\u0E23\u0E27\u0E21\u0E23\u0E32\u0E22\u0E27\u0E31\u0E19"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{proj_id}/dividend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 02. ประวัติการจ่ายเงินปันผลของกองทุน
     * @description <table style="width:100%">
     *       <tr>
     *       <th>ชื่อ Field</th>
     *       <th>รายละเอียด</th>
     *       </tr>
     *       <tr><td>last_upd_date</td><td>วันที่แก้ไขข้อมูลล่าสุด</td></tr>
     *       <tr><td>unique_id</td><td>รหัสอ้างอิงบริษัทจัดการที่เป็นผู้ส่งข้อมูล</td></tr>
     *       <tr><td>class_abbr_name</td><td>ชื่อกองทุน</td></tr>
     *       <tr><td>book_close_date</td><td>วันที่ปิดสมุดทะเบียน (YYYY-MM-DD)</td></tr>
     *       <tr><td>dividend_date</td><td>วันที่จ่ายเงินปันผล (YYYY-MM-DD)</td></tr>
     *       <tr><td>dividend_value</td><td>เงินปันผลต่อหน่วย (บาท)</td></tr>
     *       </table>
     *       <br>
     *       <p>ที่มา: สมาคมบริษัทจัดการลงทุน (AIMC)</p>
     *       <p>หมายเหตุ: ผลลัพธ์มีเฉพาะข้อมูลที่มีวันที่ปิดสมุดทะเบียน และวันที่จ่ายเงินปันผลครบถ้วนเท่านั้น </p>
     */
    get: operations["02-\u0E1B\u0E23\u0E30\u0E27\u0E31\u0E15\u0E34\u0E01\u0E32\u0E23\u0E08\u0E48\u0E32\u0E22\u0E40\u0E07\u0E34\u0E19\u0E1B\u0E31\u0E19\u0E1C\u0E25\u0E02\u0E2D\u0E07\u0E01\u0E2D\u0E07\u0E17\u0E38\u0E19"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/amc": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 03. รายชื่อบริษัทที่ส่งข้อมูลรายวัน
     * @description <table style="width:100%">
     *       <tr>
     *       <th>ชื่อ Field</th>
     *       <th>รายละเอียด</th>
     *       </tr>
     *       <tr><td>last_upd_date</td><td>วันที่แก้ไขข้อมูลล่าสุด</td></tr>
     *       <tr><td>unique_id</td><td>รหัสนิติบุคคลบริษัทจัดการ</td></tr>
     *       <tr><td>name_th</td><td>ชื่อนิติบุคคล / บุคคล (ภาษาไทย)</td></tr>
     *       <tr><td>name_en</td><td>ชื่อนิติบุคคล / บุคคล (ภาษาอังกฤษ)</td></tr>
     *       </table>
     *       <br>
     */
    get: operations["03-\u0E23\u0E32\u0E22\u0E0A\u0E37\u0E48\u0E2D\u0E1A\u0E23\u0E34\u0E29\u0E31\u0E17\u0E17\u0E35\u0E48\u0E2A\u0E48\u0E07\u0E02\u0E49\u0E2D\u0E21\u0E39\u0E25\u0E23\u0E32\u0E22\u0E27\u0E31\u0E19"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    FundAMCList: {
      /** @description วันที่แก้ไขข้อมูลล่าสุด */
      last_upd_date?: string;
      /** @description รหัสนิติบุคคลบริษัทจัดการ */
      unique_id?: string;
      /** @description ชื่อนิติบุคคล / บุคคล (ภาษาไทย) */
      name_th?: string;
      /** @description ชื่อนิติบุคคล / บุคคล (ภาษาอังกฤษ) */
      name_en?: string;
    };
    FundAMCLists: components["schemas"]["FundAMCList"][];
    FundDailyNav: {
      /** @description วันที่แก้ไขข้อมูลล่าสุด */
      last_upd_date?: string;
      /** @description วันที่ NAV (YYYY-MM-DD) */
      nav_date?: string;
      /** @description ชื่อกองทุน */
      class_abbr_name?: string;
      /** @description มูลค่าทรัพย์สินสุทธิ (บาท) */
      net_asset?: number;
      /** @description มูลค่าหน่วยลงทุน (บาท/หน่วย) */
      last_val?: number;
      /** @description มูลค่าหน่วยลงทุนของวันก่อนหน้า (บาท/หน่วย) */
      previous_val?: number;
      amc_info?: components["schemas"]["AmcInfo"][];
    };
    AmcInfo: {
      /** @description รหัสอ้างอิงบริษัทจัดการที่เป็นผู้ส่งข้อมูล */
      unique_id?: string;
      /** @description ราคาขาย (บาท/หน่วย) */
      sell_price?: number;
      /** @description ราคาซื้อคืน (บาท/หน่วย) */
      buy_price?: number;
      /** @description ราคาขายสับเปลี่ยน (บาท/หน่วย) */
      sell_swap_price?: number;
      /** @description ราคาซื้อคืนสับเปลี่ยน (บาท/หน่วย) */
      buy_swap_price?: number;
      /** @description หมายเหตุภาษาไทย */
      remark_th?: string;
      /** @description หมายเหตุภาษาอังกฤษ */
      remark_en?: string;
    };
    FundDividendHistory: {
      /** @description วันที่แก้ไขข้อมูลล่าสุด */
      last_upd_date?: string;
      /** @description วันที่ขึ้นเครื่องหมาย XD (YYYY-MM-DD) */
      book_close_date?: string;
      /** @description วันที่จ่ายเงินปันผล (YYYY-MM-DD) */
      dividend_date?: string;
      /** @description เงินปันผลต่อหน่วย (บาท) */
      dividend_value?: number;
    };
    FundDividendHistories: components["schemas"]["FundDividendHistory"][];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "01-NAV-\u0E01\u0E2D\u0E07\u0E17\u0E38\u0E19\u0E23\u0E27\u0E21\u0E23\u0E32\u0E22\u0E27\u0E31\u0E19": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description รหัส กองทุน */
        proj_id: string;
        /** @description วันที่ NAV (YYYY-MM-DD) */
        nav_date: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description FundDailyNav */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "last_upd_date": "string",
           *       "nav_date": "string",
           *       "class_abbr_name": "string",
           *       "net_asset": 0,
           *       "last_val": 0,
           *       "previous_val": 0,
           *       "amc_info": [
           *         {
           *           "unique_id": "string",
           *           "sell_price": 0,
           *           "buy_price": 0,
           *           "sell_swap_price": 0,
           *           "buy_swap_price": 0,
           *           "remark_th": "string",
           *           "remark_en": "string"
           *         }
           *       ]
           *     }
           */
          "application/json": components["schemas"]["FundDailyNav"];
        };
      };
      /** @description ไม่พบข้อมูล */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  "02-\u0E1B\u0E23\u0E30\u0E27\u0E31\u0E15\u0E34\u0E01\u0E32\u0E23\u0E08\u0E48\u0E32\u0E22\u0E40\u0E07\u0E34\u0E19\u0E1B\u0E31\u0E19\u0E1C\u0E25\u0E02\u0E2D\u0E07\u0E01\u0E2D\u0E07\u0E17\u0E38\u0E19": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description รหัส กองทุน */
        proj_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ประวัติการจ่ายเงินปันผลของกองทุน */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example [
           *       {
           *         "unique_id": "0000000569",
           *         "class_abbr_name": "ONE-UB 3",
           *         "book_close_date": "2025-01-27",
           *         "dividend_date": "2025-02-05",
           *         "dividend_value": 0.67,
           *         "last_upd_date": "2025-07-18T18:07:38.2800000+00:00"
           *       }
           *     ]
           */
          "application/json": components["schemas"]["FundDividendHistories"];
        };
      };
      /** @description ไม่พบข้อมูล */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  "03-\u0E23\u0E32\u0E22\u0E0A\u0E37\u0E48\u0E2D\u0E1A\u0E23\u0E34\u0E29\u0E31\u0E17\u0E17\u0E35\u0E48\u0E2A\u0E48\u0E07\u0E02\u0E49\u0E2D\u0E21\u0E39\u0E25\u0E23\u0E32\u0E22\u0E27\u0E31\u0E19": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description FundAMCList[] */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example [
           *       {
           *         "last_upd_date": "string",
           *         "unique_id": "string",
           *         "name_th": "string",
           *         "name_en": "string"
           *       }
           *     ]
           */
          "application/json": components["schemas"]["FundAMCLists"];
        };
      };
      /** @description ไม่พบข้อมูล */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
